version: "3"

services:
  wavemusic-bot:
    build: .
    container_name: wavemusic-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data

volumes:
  data:
